### PR TITLE
First pass at adding 'destructive' variant to buttons

### PR DESCRIPTION
**Pull request by shadoath**
Currently getting : 
```
Warning: Failed prop type: Invalid prop `variant` of value `destructive` supplied to `ForwardRef(Button)`, expected one of ["contained","outlined","text"].
```

### CODE REVIEW

**Comment by WilliamKelley** [comment]
This is a MUI v4 limitation. In order to declare a custom variant value, you would need to create a custom wrapper that captures it and doesn't pass it to the base MUI component. Otherwise MUI will always error.

Currently Button is just a re-export and customized by its theme, so you have to adhere _exactly_ to its base API.

To do the custom capturing, you can look at something like the Tag component as an example.

---

Also, all PDS v2 conversion should happen under a separate component, that starts as a duplication, is prefixed with __next__, etc.

**Comment by shadoath** [comment]
>Also, all PDS v2 conversion should happen under a separate component, that starts as a duplication, is prefixed with next, etc.

Should I do the whole folder as `__next__button` or each file in the button folder?

**Comment by WilliamKelley** [comment]
`__next__Button` and dupe the folder.

**Comment by WilliamKelley** [comment]
Also, it might be more productive to start with changing the existing variant designs first, but leaving the variant names. Then doing a custom wrapper with the actual, custom variant names and the new destructive variant. They'd be separate PRs. Otherwise you might get more trouble than its worth from skipping that.

**Comment by shadoath** [comment]
I'm thinking to close this an start again with the changes you have made removing __next__.

**Comment by WilliamKelley** [comment]
@shadoath Sure, up to you.

**Pull request closed without merging**
